# Generated by Django 5.1.6 on 2025-02-09 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_categoria_options_alter_ordenmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetail',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
