# Generated by Django 5.1.6 on 2025-02-09 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ordendetail_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordendetail',
            options={'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalles de Compra'},
        ),
        migrations.RemoveField(
            model_name='ordenmaster',
            name='detalle',
        ),
        migrations.AddField(
            model_name='ordendetail',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ordenmaster'),
        ),
    ]
